In [13]:
# Q1.1
import numpy as np
rng = np.random.default_rng()

dice_result = rng.integers(1, 7, 100)
print(dice_result[:10])

[2 6 5 5 6 1 3 6 2 2]


In [ ]:
# Q1.2
mean = np.mean(dice_result)
dst = abs(mean - 3.5)
threshold = 0.1
print("close" if dst <= threshold else "not close")

close


In [34]:
# Q2.1
size = 3
mtx = []
# 1
for _ in range(size):
    row = rng.integers(1, 10, size)
    mtx.append(row)
# 2
print(np.array(mtx))

# 3
identity = np.empty((size, size))
for i in range(size):
    for j in range(size):
        val = 0
        if i == j:
            val = 1
        identity[i][j] = val
print(identity)


[[4 2 7]
 [8 7 8]
 [6 7 2]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
# Q2.2

# 1
transposed = np.empty((size, size))
for i in range(size):
    for j in range(size):
        transposed[j][i] = mtx[i][j]
print(transposed)

# 2
is_identical = True
for i in range(size):
    for j in range(size):
        if transposed[j][i] != mtx[i][j]:
            is_identical = False
print(is_identical)



[[4. 8. 6.]
 [2. 7. 7.]
 [7. 8. 2.]]
True


In [45]:
# Q2.3
v = np.array([3, -4, 0])
# 1
L1 = sum([abs(val) for val in v]) / len(v)
print(L1)
L2 = sum([val * val for val in v]) ** 0.5
print(L2)
L3 = max([abs(val) for val in v])
print(L3)



2.3333333333333335
5.0
4
