In [ ]:
import numpy as np

rolls = np.random.randint(1, 7, 100)

print("All rolls dice: ", rolls)
print ("The first 10 rolls dice: ", rolls[:10])

All rolls dice:  [6 4 2 2 4 6 6 6 5 2 6 3 3 6 2 3 2 5 2 2 3 2 3 1 2 5 2 1 4 2 5 1 6 2 2 4 5
 2 3 4 4 5 4 1 1 4 6 2 3 4 2 5 6 2 2 1 2 2 1 4 2 4 3 1 4 5 4 6 4 4 5 3 5 6
 2 4 3 2 4 4 4 4 6 4 5 2 5 1 4 5 5 4 4 6 5 6 1 6 4 1]
The first 10 rolls dice:  [6 4 2 2 4 6 6 6 5 2]


In [3]:
mean_roll = np.mean(rolls)
print("Mean of rolls: ", mean_roll)

print("Expected value: ", 3.5)
print("Difference: ", mean_roll - 3.5)

Mean of rolls:  3.54
Expected value:  3.5
Difference:  0.040000000000000036


In [5]:
A = np.arange(1, 10).reshape(3, 3)
print("Matrix A:\n", A)
print("Shape of A:", A.shape)

I = np.eye(3)
print("Identity Matrix I:\n", I)
print("Shape of I:", I.shape)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape of A: (3, 3)
Identity Matrix I:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of I: (3, 3)


In [9]:
A_T = A.T
print("Transpose of A:\n", A_T)

i, j = 0, 1
is_equal = A[i, j] == A_T[j, i]
print(f"A[{i},{j}] == A_T[{j},{i}]:", is_equal)

Transpose of A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
A[0,1] == A_T[1,0]: True


In [10]:
v = np.array([3, -4, 0])

l1_norm = np.sum(np.abs(v))
l2_norm = np.sqrt(np.sum(v**2))
linf_norm = np.max(np.abs(v))

print("Vector v:", v)
print("L1 norm of v:", l1_norm)
print("L2 norm of v:", l2_norm)
print("Linf norm of v:", linf_norm)

Vector v: [ 3 -4  0]
L1 norm of v: 7
L2 norm of v: 5.0
Linf norm of v: 4
